version: '3'
services:
  web:
    image: ruby:3.1.2
    container_name: rails-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "bundle install && rails server -b 0.0.0.0"
    environment:
      RAILS_ENV: development
